require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Rails:
    Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Style/Next:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'app/models/invoice.rb'
    - 'app/models/recharge.rb'

Metrics/LineLength:
  Max: 155
  Exclude:
    - 'app/controllers/sessions_controller.rb'
    - 'app/models/recharge.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/models/invoice.rb'
    - 'app/models/recharge.rb'

Metrics/AbcSize:
  Max: 50








