require: rubocop-rspec
#inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Style/Encoding:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 17

Style/DoubleNegation:
  Enabled: false

Style/AndOr:
  Exclude:
    - 'app/controllers/application_controller.rb'





