# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

pontos:
  adapter: postgresql
  database: <%= Rails.application.secrets.database.name %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.secrets.database.host %>
  username: <%= Rails.application.secrets.database.username %>
  password: <%= Rails.application.secrets.database.password %>

staging:
  adapter: postgresql
  database: <%= Rails.application.secrets.database.name %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.secrets.database.host %>
  username: <%= Rails.application.secrets.database.username %>
  password: <%= Rails.application.secrets.database.password %>

production:
  adapter: postgresql
  database: <%= Rails.application.secrets.database.name %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.secrets.database.host %>
  username: <%= Rails.application.secrets.database.username %>
  password: <%= Rails.application.secrets.database.password %>

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000




# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
