# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

gimili:
  adapter: postgresql
  database: <%= Rails.application.secrets[:gimili][:database][:name] %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.secrets[:gimili][:database][:host] %>
  username: <%= Rails.application.secrets[:gimili][:database][:username] %>
  password: <%= Rails.application.secrets[:gimili][:database][:password] %>

staging:
  adapter: postgresql
  database: <%= Rails.application.secrets[:staging][:database][:name] %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.secrets[:staging][:database][:host] %>
  username: <%= Rails.application.secrets[:staging][:database][:username] %>
  password: <%= Rails.application.secrets[:staging][:database][:password] %>
  
production:
  adapter: postgresql
  database: <%= Rails.application.secrets[:production][:database][:name] %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.secrets[:production][:database][:host] %>
  username: <%= Rails.application.secrets[:production][:database][:username] %>
  password: <%= Rails.application.secrets[:production][:database][:password] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

