defaults: &defaults
  host: <%= ENV['APPS_IB_LDAP_HOST'] %>
  port: <%= ENV['APPS_IB_LDAP_PORT'] %>
  base: <%= ENV['APPS_IB_LDAP_BASE'] %>
  username: <%= ENV['APPS_IB_LDAP_USER'] %>
  password: <%= ENV['APPS_IB_LDAP_PASS'] %>
  group: <%= ENV['APPS_IB_LDAP_GROUP'] %>

pontos:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults



