defaults: &defaults
  host: <%= ENV.fetch('APPS_IB_LDAP_HOST') %>
  port: <%= ENV.fetch('APPS_IB_LDAP_PORT') %>
  base: <%= ENV.fetch('APPS_IB_LDAP_BASE') %>
  username: <%= ENV.fetch('APPS_IB_LDAP_USER') %>
  password: <%= ENV.fetch('APPS_IB_LDAP_PASS') %>
  group: <%= ENV.fetch('APPS_IB_LDAP_GROUP') %>

pontos:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
  
  

