pontos:
  host: Rails.application.secrets.ldap_host
  port: Rails.application.secrets.ldap_port
  username: Rails.application.secrets.ldap_username
  password: Rails.application.secrets.ldap_password
  base: Rails.application.secrets.ldap_base
  group_base: OU=ILL Billing,OU=Groups,OU=University Library,DC=AD,DC=UCSD,DC=EDU
  
  

  