pontos:
  host: ldap.ad.ucsd.edu
  port: "636"
  username: lib-LDAP@ad.ucsd.edu
  password: Roow1pee
  base: OU=University Library,DC=AD,DC=UCSD,DC=EDU
  group_base: CN=ILL Billing,OU=Groups,OU=University Library,DC=AD,DC=UCSD,DC=EDU

development:
  host: xxxxxx
  port: "xxx"
  username: xxx
  password: xxx
  base: OU=University Library,DC=AD,DC=UCSD,DC=EDU
  group_base: OU=ILL Billing,OU=Groups,OU=University Library,DC=AD,DC=UCSD,DC=ED
  